apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: deepseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_BASE_URL
              value: "https://example.com"

---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: deepseek
spec:
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
